app/src/Entity/PlantPresets.php
<?php

namespace App\Entity;

use App\Repository\PlantPresetsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SettingsPlantRepository::class)
 */
class PlantPresets
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $name;

    /**
     * @ORM\Column(type="float")
     */
    private $moisture;

    /**
     * @ORM\Column(type="integer")
     */
    private $temperature;

    /**
     * @ORM\Column(type="integer")
     */
    private $light_level;

    /**
     * @ORM\Column(type="integer")
     */
    private $light_duration;

    /**
     * @ORM\Column(type="integer")
     */
    private $user_id;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getMoisture(): ?float
    {
        return $this->moisture;
    }

    public function setMoisture(float $moisture): self
    {
        $this->moisture = $moisture;

        return $this;
    }

    public function getTemperature(): ?int
    {
        return $this->temperature;
    }

    public function setTemperature(int $temperature): self
    {
        $this->temperature = $temperature;

        return $this;
    }

    public function getLightLevel(): ?int
    {
        return $this->light_level;
    }

    public function setLightLevel(int $light_level): self
    {
        $this->light_level = $light_level;

        return $this;
    }

    public function getLightDuration(): ?int
    {
        return $this->light_duration;
    }

    public function setLightDuration(int $light_duration): self
    {
        $this->light_duration = $light_duration;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

app/src/Controller/PlantPresetsController.php
<?php

namespace App\Controller;

use App\Entity\PlantPresets;
use App\Entity\User;
use App\Entity\WaterLevel;
use App\Form\PlantPresetsFormType;
use App\Repository\LightLevelRepository;
use App\Repository\NotificationRepository;
use App\Repository\PlanterRepository;
use App\Repository\PlantPresetsRepository;
use App\Repository\SoilMoistureRepository;
use App\Repository\WaterLevelRepository;
use DateInterval;
use DateTimeZone;
use phpDocumentor\Reflection\Types\This;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PlantPresetsController extends BaseController
{
    private $planterRepository;
    private $plantPresetsRepository;

    public function __construct(
        PlantPresetsRepository $plantPresetsRepository,
        PlanterRepository $planterRepository
    )
    {
        $this->planterRepository = $planterRepository;
        $this->plantPresetsRepository = $plantPresetsRepository;
    }

    /**
     * @Route("/plant-presets", name="plant_presets")
     * @return Response
     */
    public function index(): Response
    {
        $settings = $this->plantPresetsRepository->findByUserId($this->getUser()->getId());

        return $this->render('PlantPresets/index.html.twig', [
            'settings' => $settings,
        ]);
    }

    /**
     * @Route("/plant-presets/new", name="plant_presets_new")
     */
    public function new(Request $request): Response
    {
        $SettingsPlant = new PlantPresets();
        $form = $this->createForm(PlantPresetsFormType::class, $SettingsPlant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $SettingsPlant->setName($form->get('name')->getData());
            $SettingsPlant->setLightDuration($form->get('light_duration')->getData());
            $SettingsPlant->setLightLevel($form->get('light_level')->getData());
            $SettingsPlant->setMoisture($form->get('moisture')->getData());
            $SettingsPlant->setTemperature($form->get('temperature')->getData());
            $SettingsPlant->setUserId($this->getUser()->getId());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($SettingsPlant);
            $entityManager->flush();
            // do anything else you need here, like send an email

            return $this->redirectToRoute('plant_presets');
        }

        return $this->render('PlantPresets/new.html.twig', [
            'presetsForm' => $form->createView(),
        ]);
    }

    /**
     * @Route("/plant-presets/edit/{id}", name="plant_presets_edit")
     */
    public function edit(Request $request, $id): Response
    {
        $plantPreset = $this->plantPresetsRepository->findOneById($id);
        if ($plantPreset === null){
            return $this->renderUnauthorised();
            //todo neexistuje
        }else if (!$this->canEdit($this->getUser(), $plantPreset)){
            return $this->renderUnauthorised();
        }
        $form = $this->createForm(PlantPresetsFormType::class, $plantPreset)
            ->add( 'delete', SubmitType::class, ['label' => 'delete']);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $delete = $form->get('delete')->isClicked();
            if ($delete){
                if (!empty($this->planterRepository->findByPlantPresetId($plantPreset->getId()))){
                    $this->addFlash('danger', 'can\'t delete. some planter is using this');
                }else{
                    $entityManager->remove($plantPreset);
                    $entityManager->flush();
                    $this->addFlash('success', 'Deleted.');
                }

            }else{
                $plantPreset->setName($form->get('name')->getData());
                $plantPreset->setLightDuration($form->get('light_duration')->getData());
                $plantPreset->setLightLevel($form->get('light_level')->getData());
                $plantPreset->setMoisture($form->get('moisture')->getData());
                $plantPreset->setTemperature($form->get('temperature')->getData());
                $plantPreset->setUserId($this->getUser()->getId());
                $entityManager->flush();

                $this->addFlash('success', 'Updated.');
            }



            return $this->redirectToRoute('plant_presets');
        }

        return $this->render('PlantPresets/edit.html.twig', [
            'presetsForm' => $form->createView(),
            'plantPreset' => $plantPreset,
            'test' => $id
        ]);
    }

    private function renderUnauthorised(){
        return $this->render('general/unauthorised.html.twig', [
            'message' => 'You are not authorised to edit this :('
        ]);
    }


    private function canEdit(User $user, PlantPresets $settings): bool{
        return $user->getId() === $settings->getUserId();
    }

}

app/templates/PlantPresets/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit plant: {{ plantPreset.getName }}{% endblock %}


{% block body %}
    {% for flashError in app.flashes('verify_email_error') %}
        <div class="alert alert-danger" role="alert">{{ flashError }}</div>
    {% endfor %}

    <div class="content-wrapper">
        <h1>Edit plant preset:  <b>{{ plantPreset.getName }}</b></h1>
        <div class="block-wrapper">
        {{ form_start(presetsForm) }}
            <div class="form-group">
                {{ form_label((presetsForm.name)) }}
                {{ form_widget(presetsForm.name, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(presetsForm.name) }}
            </div>
            <div class="form-group">
                {{ form_label((presetsForm.moisture)) }}
                {{ form_widget(presetsForm.moisture, {'attr': {'class': 'form-control input-unit'}}) }}<span class=" input-unit">%</span>
                {{ form_errors(presetsForm.moisture) }}
            </div>
            <div class="form-group">
                {{ form_label((presetsForm.temperature)) }}
                {{ form_widget(presetsForm.temperature, {'attr': {'class': 'form-control input-unit'}}) }}<span class="input-unit">°C</span>
                {{ form_errors(presetsForm.temperature) }}
            </div>
            <div class="form-group">
                {{ form_label((presetsForm.light_level)) }}
                {{ form_widget(presetsForm.light_level, {'attr': {'class': 'form-control input-unit'}}) }}
            </div>
            <div class="form-group">
                {{ form_label((presetsForm.light_duration)) }}
                {{ form_widget(presetsForm.light_duration, {'attr': {'class': 'form-control'}}) }}
            </div>
            {{ form_widget(presetsForm.save, {'attr': {'class': 'btn btn-primary'}}) }}
            {{ form_widget(presetsForm.delete, {'attr': {'class': 'btn btn-danger' , 'onclick': 'return confirm("Are you sure?")'}}) }}
        {{ form_end(presetsForm) }}
        </div>
    </div>
{% endblock %}

app/templates/PlantPresets/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Plant presets{% endblock %}

{% block body %}
<div class="content-wrapper text-center">
    <h1>Plant presets</h1>
    <div>
        <div class="table-wrapper">
            <table class="fl-table">
                <thead>
                <tr>
                    <th>name</th>
                    <th>moisture</th>
                    <th>temperature</th>
                    <th>min light level</th>
                    <th>light duration</th>
                    <th>action</th>
                </tr>
                </thead>
                <tbody>
                {% if  settings is empty %}
                    <tr>
                        <td colspan="7">you don't have any plant presets yet :(</td>
                    </tr>
                {% endif %}
                {% for c in settings %}
                    <tr>
                        <td>{{ c.name }}</td>
                        <td>{{ c.moisture}} %</td>
                        <td>{{ c.temperature }} °C</td>
                        <td>{{ c.lightLevel }} lux</td>
                        <td>{{ c.lightDuration}} h</td>
                        <td><a class="btn btn-dark btn-sm" href="{{ path('plant_presets_edit' , {id: c.id}) }}">edit</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <a class="btn btn-primary btn-block" href="{{ path('plant_presets_new') }}">add new</a>
        </div>
</div>
{% endblock %}

app/templates/PlantPresets/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New plant preset{% endblock %}

{% block body %}
    {% for flashError in app.flashes('verify_email_error') %}
        <div class="alert alert-danger" role="alert">{{ flashError }}</div>
    {% endfor %}

    <div class="content-wrapper">
        <h1>New plant preset</h1>
        <div class="block-wrapper">
            {{ form_start(presetsForm) }}
            <div class="form-group">
                {{ form_label((presetsForm.name)) }}
                {{ form_widget(presetsForm.name, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(presetsForm.name) }}
            </div>
            <div class="form-group">
                {{ form_label((presetsForm.moisture)) }}
                {{ form_widget(presetsForm.moisture, {'attr': {'class': 'form-control input-unit'}}) }}<span class=" input-unit">%</span>
                {{ form_errors(presetsForm.moisture) }}
            </div>
            <div class="form-group">
                {{ form_label((presetsForm.temperature)) }}
                {{ form_widget(presetsForm.temperature, {'attr': {'class': 'form-control input-unit'}}) }}<span class="input-unit">°C</span>
                {{ form_errors(presetsForm.temperature) }}
            </div>
            <div class="form-group">
                {{ form_label((presetsForm.light_level)) }}
                {{ form_widget(presetsForm.light_level, {'attr': {'class': 'form-control input-unit'}}) }}
            </div>
            <div class="form-group">
                {{ form_label((presetsForm.light_duration)) }}
                {{ form_widget(presetsForm.light_duration, {'attr': {'class': 'form-control'}}) }}
            </div>
            {{ form_widget(presetsForm.save, {'attr': {'class': 'btn btn-primary'}}) }}
            {{ form_end(presetsForm) }}
        </div>
    </div>

{% endblock %}